// src/app/layout.tsx
import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { StoreProvider } from "../providers/StoreProvider";
import ThemeWrapper from "../features/themes/ThemeWrapper";

const manrope = localFont({
  src: [
    { path: "../../public/fonts/Manrope/static/Manrope-Regular.ttf", weight: "400" },
    { path: "../../public/fonts/Manrope/static/Manrope-Medium.ttf", weight: "500" },
    { path: "../../public/fonts/Manrope/static/Manrope-SemiBold.ttf", weight: "600" },
    { path: "../../public/fonts/Manrope/static/Manrope-Bold.ttf", weight: "700" },
  ],
  variable: "--font-manrope",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={manrope.variable}>
        <StoreProvider>
          <ThemeWrapper>{children}</ThemeWrapper>
        </StoreProvider>
      </body>
    </html>
  );
}
