"""create tables

Revision ID: 1e12ed05d385
Revises: 6ac1a429df56
Create Date: 2026-04-20 02:23:39.038415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e12ed05d385'
down_revision = '6ac1a429df56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('articles_image_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'images', ['main_image_id'], ['id'])
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('articles_image_id_fkey'), 'images', ['image_id'], ['id'])
        batch_op.drop_column('main_image_id')

    # ### end Alembic commands ###
