"""create tables

Revision ID: 2e53aac4deab
Revises: 29f085b067e1
Create Date: 2026-04-18 23:15:00.986373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e53aac4deab'
down_revision = '29f085b067e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cosplays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cosplays', schema=None) as batch_op:
        batch_op.drop_column('favorite_color')

    # ### end Alembic commands ###
