"""create tables

Revision ID: 6420975bd2ca
Revises: 2e53aac4deab
Create Date: 2026-04-19 15:29:41.686830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6420975bd2ca'
down_revision = '2e53aac4deab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('seller_instagram', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('seller_instagram')
        batch_op.drop_column('seller_phone')

    # ### end Alembic commands ###
