"""create tables

Revision ID: c8ca1bc6b021
Revises: 1e12ed05d385
Create Date: 2026-04-20 02:36:11.075582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ca1bc6b021'
down_revision = '1e12ed05d385'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_contents', schema=None) as batch_op:
        batch_op.create_index('ix_event_content_event_id', ['event_id'], unique=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_image_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('events_image_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'images', ['main_image_id'], ['id'])
        batch_op.drop_column('description')
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('events_image_id_fkey'), 'images', ['image_id'], ['id'])
        batch_op.drop_column('main_image_id')

    with op.batch_alter_table('event_contents', schema=None) as batch_op:
        batch_op.drop_index('ix_event_content_event_id')

    op.drop_table('event_contents')
    # ### end Alembic commands ###
